namespace Y5Lib
{
    public enum VoicerCategory
    {
        StepWalk = 0,               // "step_walk"
        StepRun = 1,                // "step_run"
        StepDown = 2,               // "step_down"
        StepBullet = 3,             // "step_bullet"
        StepDancer = 4,             // "step_dancer"
        StepCommon = 5,             // "step_common"
        Haichi = 6,                 // "haichi"
        BattleSe = 7,               // "battle_se"
        BtlVoice = 8,               // "btl_voice"
        BtlHelp = 9,                // "btl_help"
        BtlLoser = 10,              // "btl_loser"
        BtlEnc = 11,                // "btl_enc"
        AdvCommonVoice = 12,        // "adv_common_voice"
        Stage = 13,                 // "stage"
        Gaya = 14,                  // "gaya"
        Stalker = 15,               // "stalker"
        SnowmobileVoice = 16,       // "snowmobile_voice"
        Talk = 17,                  // "talk"
        Enc01Revile = 18,           // "enc01_revile"
        Enc02Dec = 19,              // "enc02_dec"
        Fighter = 20,               // "fighter"
        Chaser = 21,                // "chaser"
        Navi = 22,                  // "navi"
        Reaction = 23,              // "reaction"
        Enc10Loser = 24,            // "enc10_loser"
        SidestTaxiRacePEngine = 25, // "sidest_taxi_race_p_engine"
        SidestTaxiRaceEEngine = 26, // "sidest_taxi_race_e_engine"
        SidestYukiyamaYuki = 27,    // "sidest_yukiyama_yuki"
        Btlgaya = 28,               // "btlgaya"
        AdvPlayer = 29,             // "adv_player"
        VehicleCar = 30,            // "vehicle_car"
        Enc00Call = 31,             // "enc00_call"
        BulletHit = 32,             // "bullet_hit"
        WeakpointHit = 33,          // "weakpoint_hit"
        BtllongEnc = 34,            // "btllong_enc"
        Enc03Lost = 35,             // "enc03_lost"
        TsukkomiVoice = 36,         // "tsukkomi_voice"
        HockeyVoice = 37,           // "hockey_voice"
        PrintclubVoice = 38,        // "printclub_voice"
        TaikoVoice = 39,            // "taiko_voice"
        Arena = 40,                 // "arena"
        Eat = 41,                   // "eat"
        RamenVoice = 42,            // "ramen_voice"
        Dancer = 43,                // "dancer"
        TaxiCity = 44,              // "taxi_city"
        TaxiRacer = 45,             // "taxi_racer"
        Baseball = 46,              // "baseball"
        MinigGolfTrainingVoice = 47,// "minig_golf_training_voice"
        TaxiTalker = 48,            // "taxi_talker"
        TaxiWalker = 49             // "taxi_walker"
    }
}
